# Generated by Django 5.0 on 2024-10-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
